AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./searchphotos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::012453256069:role/admin'
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./indexphotos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::012453256069:role/admin'
